### ISSUE TITLE
Project #3- Artpear

### ISSUE THREAD

**Issue by patrickthesailorman** [ga-wdi-pvd/project3-gallery#1]
# Artpear

[Artpear front-end](https://github.com/patrickthesailorman/artpear-front-end)
[Artpear back-end](https://github.com/patrickthesailorman/artpear-back-end)

**Comment by JosephinaTavera** [comment]
GREAT APP, technical requirements met.  

LOVE that you had thought of using Mocha/Chai for testing. 

Be more specific on unsolved problems or major hurdles.  List steps that have yet to be completed.  This will provide people with a better image of your ideas for this project.  

Add more information in the installation notes, such as what they will see when clicking on the links.   I had clicked them and did not know what to expect. 

A link to the repo for your back-end is missing from the README document in the front-end repo.   

Link to the deployed back-end app not working in the README document of the back-end repo.  

Great use of comments in the index.html file.  Replicate that in your other files.   It will be helpful to understand what the code is doing at a quick glance.

**Comment by JosephinaTavera** [comment]
# Evaluation Criteria

| Category                        | Incomplete                                                                                                                    | Progressing                                                                                                                                                                                           | Performing                                                                                                                                                             | Excelling                                                                                                                                                                                                          |
|---------------------------------|-------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Back-end Technology             |                                                                |                                                                                                                                                                           | Includes 2 models                                                                                                                                                      |                                                         |
| Front-end Technology            |                                                                                              |                                                                                                                                              | Front-end makes appropriate use of Angular controllers and states with ui-router.                                                        |                                                                               |
| Code Quality                    |                                                                                            |                                      |                                                                                           | No major code quality issues, Angular code follows techniques such as separation of concerns, abstraction, and encapsulation                                                   |
| Deployment and Functionality    |                                                      |                                                                          | Application contains no major errors, is deployed correctly, and contains a custom Heroku app name appropriate for the app.                                            |             |
| Planning / Process / Submission |  |  | Submission contains clear evidence of planning, adequate documentation, include all from previous category, as well as additional information such as unsolved issues. |  |


<!-- Generated from http://www.tablesgenerator.com/markdown_tables -->
