### ISSUE TITLE
let projectThreeGroup = ["Dara", "Alyssa", "Cliff"] 

### ISSUE THREAD

**Issue by awanderlyss** [ga-wdi-pvd/project3-gallery#2]
let frontEndReadme = "https://github.com/cliftonh02/empire_co_angular/blob/master/README.md"

let backEndReadme = "https://github.com/awanderlyss/empire_co_api/blob/master/README.md"

WORDDD!!

**Comment by ahnuce** [comment]
oh yea? array of names?

**Comment by awanderlyss** [comment]
@ahnuce dont be a hater...

**Comment by danman01** [comment]
Review:

Backend Technology:
Well organized backend. 2 models. Incorporate passport.
3: Excelling 

Front end Technology:
nice attempt with other libraries for making it look good, but if app doesn’t work as expected, the looks aren’t that important.
1.5 - Progressing

code quality:
backend - well organized, well formatted, separation of concerns.
3 - Excelling
front end: 
includes unused files, commented out code, non functional code
1.5 - Progressing

deployment and functionality:
1.5 - Progressing / Performing. Backend is deployed and working nicely through postman. Able to CRUD products. Front end cannot get past login. Not sure if controllers are functioning

Planning / Submission:
Evidence of a little bit of planning. Schema is well planned. You did not talking about issues or things you wanted to get done in the readme. Some good commit messages, some signs of branching, some signs of peer review. You could do better on all of the git areas: commit messages, branch naming and single feature / bug fix per branch (backend looks good with commits).
Did you use Trello or another project management tool?
Who managed code quality?
Performing: 2 

Overall score: Performing - 2

Notes:
Talk about your issues in your readme
Work to get the basic front end (bronze) then move up to passport and silver / gold levels of functionality.
Remove unused or duplicate files. Remove code that is commented out.
Make better git commits
Make better use of branching - single responsibility of branches and name them appropriately
Peer review code coming in. Hold yourself and team up to high standards. 
Hold each other accountable for functionality - set deadlines and stick to them.
Link to Trello / talk about how you used Trello or project management tool
Cliff, Dara: contribute more to back end. Alyssa make sure team members are making commits.
Alyssa: contribute more to front end. Make sure other team members are understanding their jobs / roles and not getting stuck on anything.

We can meet and go over this if you guys want to, just let me know when's a good time. We can also work more on this project if you would like to after project 4 and get it ready for your portfolios.
