### ISSUE TITLE
David, Erik, Mason

### ISSUE THREAD

**Issue by mwb86** [ga-wdi-pvd/project3-gallery#3]
front = https://github.com/mwb86/gofilter
back = https://github.com/mwb86/filterbackend

**Comment by tvcrawley** [comment]
# Evaluation Criteria

| Category                        | Incomplete                                                                                                                    | Progressing                                                                                                                                                                                           | Performing                                                                                                                                                             | Excelling                                                                                                                                                                                                          |
|---------------------------------|-------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Back-end Technology             |                                                                |                                                                                                                                                                           | Includes 2 models                                                                                                                                                      |                                                     |
| Front-end Technology            |                                                                                                        |                                                                                                                                                   | Front-end makes appropriate use of Angular controllers and states with ui-router.                                                        |                                                                                     |
| Code Quality                    |                                                                                            |                                                          | Code is well-formatted, well-named, and contains few style / quality issues                                                                                            |                                                  |
| Deployment and Functionality    |                                                               |                                                                          | Application contains no major errors, is deployed correctly, and contains a custom Heroku app name appropriate for the app.                                            |             |
| Planning / Process / Submission |  | | Submission contains clear evidence of planning, adequate documentation includes setup instructions, description of application functionality and link to deployed application, as well as additional information such as unsolved issues. |  |


<!-- Generated from http://www.tablesgenerator.com/markdown_tables -->

**Comment by tvcrawley** [comment]
@mwb86 @dmozzoni @erikslewis

Great job on the app! The idea is unique and definitely stands out from projects previously seen.

Areas to work on:
- Separation of concerns for the backend is well done; **frontend needs work**. 
  - You want as little script tags with heavy functionality in your html as possible.
- Link to deployed app should contain the app name
  - https://morning-wildwood-94098.herokuapp.com/ doesn't give the user a hint on what your app is about
- More commits!
  - It's not uncommon for a group project to have 100+ commits
  - Every little win/breakthrough deserves a commit
