### ISSUE TITLE
Anusone Rafael Julie

### ISSUE THREAD

**Issue by ahnuce** [ga-wdi-pvd/project3-gallery#4]
Project 3

front end: 
https://github.com/ahnuce/16barsFrontEnd

back end:
https://github.com/ahnuce/16barsBackEnd

**Comment by danman01** [comment]
Project 3 feedback - 16 Bars 

Please share this with your team.

I like this idea. Could be expanded with other features and easily shared with writers. Writing and displaying poetry is a great chance to use some two way data binding and responsive user interface design. Keep developing this project and add it to your portfolios. We will have at least 1.5 days in class next week to finish up prior projects. Take that time to finish up this.

Grading:
Back end technology used:
1/4 - lacking more than one model. Some additional models could be comments, likes / hearts, users. Nice job creating api routes and hooking up mongo / mongoose.

Front end technology used
2/4 - performing; makes use of angular controllers, states and ui-router. Could take advantage of factories, services, directives, etc. Nice use of templates, ng-model, ng-submit, ng-click, $state, $http and $scope.

Code Quality
2/4 - well formatted, well documented, does contain some commented out code. Could be a simple clean up. Imagine you were turning this in for inspection. Once your code works, refactor. Make your code confident and a joy to read. Add tests if you are inclined. It will make you stand out from everyone else and make your code solid.

`Poem.create` - `res.json` and `res.redirect` in same action?
Many undhandled promise reject warnings…

Check dev console for warnings, errors and log statements.

Deployment and functionality
2/4 - almost performing; no major errors, is deployed correctly, has custom Heroku app name. Front end heroku link in readme does not allow functionality of app: https://sixteen-bars.herokuapp.com/#/poems. After messing around with CORS locally, I was able to get app working. Front end deployed on github pages does not access the node/express api.

Nice use of extracting `rootURL` to a variable, but not working for localhost. Provide a conditional based on environment, or set up variable in .env file and access like: process.env.rootURL.

Create poem returns json object to console, but not to user interface

Planning and submission
2/4 - does contain evidence of planning (ERD diagram), app summary, notes of what tech is used, what could be added. Each section could use attention to more detail. 

erd diagram:
- great that you did this planning step. keep it updated as you work on your project. It should be a source of truth.
- one to many: the many side has the foreign key of the one side (user_id is in the comments table). 
- specify the data type as well
- make sure the names are correct
- use appropriate drawing lines for 1 to many, then you don’t need to write the words. 

Front End readme: 

- add install and usage instructions
- add known issues / stretch goals. Why doesn’t the github interface work?

How is front end app deployed? instructions for deploying? what if a new team member joined…how would you get them up to speed quickly working on this project?

Add instructions for testing front end locally.

Backend readme:

Nice readme with many details. Cleanly laid out. Some spelling errors. Could benefit for more in-depth dive into many sections:

instructions:
- install instructions
  - notice how many libraries always start with step one, even if it’s understood by the community (i.e. npm install —save is likely listed in every npm package readme) 
- include how to seed db
 
usage instructions
  - make it idiot-proof
  - code error for localhost: include mongodb url and instructions for creating mongoldb
  - the endpoints look nice in tables. What params are required by each method?

tech used:
 - make these hyperlinks

known issues:
 - why is this an issue? what stopped you from making it happen?

stretch goals:
 - `list any feature / goal you have for the project that you didn’t get a chance to implement
